### ISSUE TITLE
How to test the megadiff_changes dataset more conveniently?

### ISSUE THREAD

**Issue by squareRoot3** [oceaneLIU/GABoost#1]
Hello!

I'm the author of SLOTAlign. I've noticed that the megadiff_changes dataset contains many graph pairs. Could you share the scripts to test them together? Additionally, would you be able to share the scripts for baselines like SLOTAlign to run on this dataset?

**Comment by squareRoot3** [comment]
hi?

**Comment by oceaneLIU** [comment]
## How to Test the `megadiff_changes` Dataset  

Thank you for your interest in the `megadiff_changes` dataset! Below, I’ll explain how you can write a simple Bash script to test this dataset. This structure can also be adapted for other baselines beyond `SCMN+GABoost`.  

### Dataset Structure  

The dataset is organized as follows:  
- **Directories**: `perm-megadiff-1` to `perm-megadiff-4`, each representing a permutation of node IDs.  
- **Subfolders**: Contain 5 levels of changed lines, named `5changelines`, `10changelines`, ..., `40changelines`.  
- **Samples**: Each subfolder includes two testable samples, `sample1` and `sample2`.  

### Example Bash Script  

Here’s a Bash script to loop through all combinations of `n`, `changelines`, and `sample_id` and run `SCMN+GABoost`.  

```bash
#!/bin/bash

for n in {1..4}; do
    for changelines in 5 10 20 30 40; do
        for sample_id in 1 2; do
            folder_name="./dataset/megadiff_changes/perm-megadiff-${n}/${changelines}changelines/sample${sample_id}/"
            python runGABoost.py --mode SCMN+GABoost \
                --input_g0_node "${folder_name}left_node_file" \
                --input_g0_edge "${folder_name}left_edge_file" \
                --input_g1_node "${folder_name}right_node_file" \
                --input_g1_edge "${folder_name}right_edge_file" \
                --ground_truth_alignment "${folder_name}true_matching"
        done
    done
done

**Comment by squareRoot3** [comment]
Sincerely thanks!
